#!/bin/sh

if [ "$BENCH_OUTPUT" = '' ]; then
    >&2 echo 'Missing BENCH_OUTPUT environment variable.'
    exit 1
fi

/opt/build/bench/128-bit-trace-ids/tracer/tracer >"$BENCH_OUTPUT" &
tracer_pid=$?

trap 'kill "$tracer_pid"' INT
wait
